#Code Generated by TestGenx v.1.0
#ANCIT CONSULTING
#Date : Wed Feb 12 11:32:23 IST 2020
#Author : Tejas

from __future__ import print_function
import can
import time
import cantools
#from pynput import keyboard
from pynput import mouse
#import keyboard
#x = 20
def send_one():
        filename = '/home/thomas/Pictures/comfort.dbc'
        db = cantools.database.load_file(filename)
        bus = can.interface.Bus(bustype='socketcan',channel='vcan0',bitrate=500000)

	# Message : VehicleMotion

        example_message = db.get_message_by_name('VehicleMotion')
        data = example_message.encode({'EngineRunning':0,'CrashDetected':1,'Velocity':10})
message = can.Message(arbitration_id=example_message.frame_id, data=data, is_extended_id=False)
try:
	task = bus.send_periodic(message,0.20) # cycle time
	print(" VehicleMotion Message sent on {}".format(bus.channel_info))
except can.CanError:
	print("Message NOT sent")

class MyException(Exception): pass

def on_click(x, y, button, pressed):
    if button == mouse.Button.left:
        raise MyException(button)

# Collect events until released
with mouse.Listener(
        on_click=on_click) as listener:
    try:
        listener.join()
    except MyException as e:
        print('{0} was clicked'.format(e.args[0]))


